.\" Manpage for emojify
.\" Contact elijah@jschutz.net to correct errors or typos
.TH emojify 1 "24 September 2016" "" "emojify"
.SH NAME
\fIemojify\fR \- inserts random emojis on every face in a png image.
.SH SYNOPSIS
emojify [\fB\-f\fR\||\fB\-\-fast\fR] [\fIfile\fR]
.SH DESCRIPTION
emojify is a tool for creating images in which every face is replaced with an emoji. So far it only supports PNG images and Apple emojis from emojipedia.org/apple, however this may change in the future.
.SH OPTIONS
.TP
.BR \-f ", "\-\-fast
Specifies fast RGBA saving for the output image.
.TP
.BR \fB\-n\fR ", "\fB\-\-name " "\fR[\fIname\fR]
Specify the name of the output file.
.SH BUGS
No known bugs.
.SH AUTHOR
Elijah Schutz (elijah@jschutz.net)
